on:
  workflow_call:
    inputs:
      entry:
        required: true
        type: string
      os:
        required: true
        type: string
      node:
        required: true
jobs:
  reusable_workflow_job:
    runs-on: ${{ inputs.os }}

    env:
      BATI_TEST: true
      TEST_AUTH0_CLIENT_ID: ${{ secrets.TEST_AUTH0_CLIENT_ID }}
      TEST_AUTH0_ISSUER_BASE_URL: ${{ secrets.TEST_AUTH0_ISSUER_BASE_URL }}
      TEST_FIREBASE_ACCOUNT: ${{ secrets.TEST_FIREBASE_ACCOUNT }}
      TEST_FIREBASE_USER_UID: ${{ secrets.TEST_FIREBASE_USER_UID }}
      TEST_GITHUB_CLIENT_ID: ${{ secrets.TEST_GITHUB_CLIENT_ID }}
      TEST_GITHUB_CLIENT_SECRET: ${{ secrets.TEST_GITHUB_CLIENT_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node }}

      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v1.5

      - uses: oven-sh/setup-bun@v2
        name: Install bun
        with:
          bun-version: "1.1.27"

      - name: Download Bati CLI
        uses: actions/download-artifact@v4
        with:
          name: bati-cli-${{ inputs.os }}-${{ inputs.node }}
          path: ./bati-cli

      - name: Download Bati tests
        uses: actions/download-artifact@v4
        with:
          name: bati-tests-${{ inputs.os }}-${{ inputs.node }}
          path: ./bati-tests

      - name: Download tests-utils
        uses: actions/download-artifact@v4
        with:
          name: tests-utils-${{ inputs.os }}-${{ inputs.node }}
          path: ./bati-tests-utils

      - name: Download tests-files
        uses: actions/download-artifact@v4
        with:
          name: tests-files-${{ inputs.os }}-${{ inputs.node }}
          path: ./bati-tests-files

      - name: Generate dynamic composite action
        run: node ./scripts/gen-composite-workflow-action.js '${{ inputs.entry }}'

      - name: Run all tests
        id: gen
        uses: ./.github/actions/bati-gen
        with:
          os: ${{ inputs.os }}
          node: ${{ inputs.node }}

      - name: Cleanup
        if: always() && steps.gen.outcome != 'success'
        shell: bash
        run: rm -rf ./.github/actions/bati-gen
