name: Tests

on:
  pull_request:
    paths-ignore:
      - 'website/**'
  push:
    # Ensures cache is computed on main branch so that it can be reused on all PRs
    branches: [ "main" ]
    paths-ignore:
      - 'website/**'

jobs:
  build-and-tests:
    runs-on: ${{ matrix.os }}

    # Uncomment to debug discrepancies between published package and local one
#    services:
#      verdaccio:
#        # See https://github.com/actions/runner/issues/822#issuecomment-1524826092
#        image: ${{ (matrix.os == 'ubuntu-latest') && 'verdaccio/verdaccio' || '' }}
#        ports:
#          - 4873:4873

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [20]
        include:
          - os: ubuntu-latest
            node: 18
          - os: ubuntu-latest
            node: 22
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false

      - uses: oven-sh/setup-bun@v2
        name: Install bun
        with:
          bun-version: "1.1.20"

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: mkdir temp folder
        run: mkdir -p ${{ runner.temp }}/bati-cache

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - uses: actions/cache@v4
        # REALLY slow on windows
        if: matrix.os != 'windows-latest'
        name: Setup bun cache
        with:
          path: ~/.bun/install/cache
          # Uses pnpm hash to avoid too many cache creations
          key: ${{ runner.os }}-bun-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - uses: actions/cache@v4
        name: Setup Bati cache
        with:
          path: ${{ runner.temp }}/bati-cache
          key: ${{ runner.os }}-${{ matrix.node }}-bati-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-bati-cache-

      - uses: actions/cache@v4
        name: Setup Turborepo cache
        with:
          path: .turbo
          key: ${{ runner.os }}-${{ matrix.node }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-turbo-

#      - name: Install global dependencies
#        if: matrix.os == 'ubuntu-latest'
#        run: pnpm install --global npm-cli-login

#      - name: Login to verdaccio
#        if: matrix.os == 'ubuntu-latest'
#        run: npm-cli-login
#        env:
#          NPM_USER: bati
#          NPM_PASS: bati
#          NPM_EMAIL: bati@example.com
#          NPM_REGISTRY: http://localhost:4873

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm run build

#      - name: Release in local repo
#        if: matrix.os == 'ubuntu-latest'
#        run: pnpm run release:local

      - name: Run tests
        run: pnpm run test

      - name: Run e2e tests
        run: pnpm run test:e2e --keep --summarize ${{ (matrix.os == 'windows-latest' || matrix.os == 'macos-latest') && '--filter solid' || '' }}
        env:
          TEST_AUTH0_CLIENT_ID: ${{ secrets.TEST_AUTH0_CLIENT_ID }}
          TEST_AUTH0_ISSUER_BASE_URL: ${{ secrets.TEST_AUTH0_ISSUER_BASE_URL }}
          TEST_FIREBASE_ACCOUNT: ${{ secrets.TEST_FIREBASE_ACCOUNT }}
          TEST_FIREBASE_USER_UID: ${{ secrets.TEST_FIREBASE_USER_UID }}

      - name: Archive summary
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ matrix.node }}-summary
          path: |
            ${{ runner.temp }}/bati/.turbo/runs/*.json

  clean-cache:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        key:
          - Windows-20-bati-cache
          - Windows-20-turbo
          - Windows-pnpm-store
          - macOS-20-bati-cache
          - macOS-20-turbo
          - macOS-pnpm-store
          - macOS-bun
          - Linux-20-bati-cache
          - Linux-20-turbo
          - Linux-pnpm-store
          - Linux-bun
          - Linux-18-bati-cache
          - Linux-18-turbo
          - Linux-22-bati-cache
          - Linux-22-turbo
    steps:
      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache
          
          echo "Fetching list of cache keys with key: $key"
          cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH --sort last-used --order desc --key $KEY -L 100 | cut -f 1)

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          
          # Convert the list of cache keys to an array
          cacheKeysArray=($cacheKeysForPR)

          # Get the number of cache keys
          cacheKeyCount=${#cacheKeysArray[@]}

          # Delete all cache keys except the last one
          echo "Deleting caches for key: $key..."
          for ((i=0; i<cacheKeyCount-1; i++))
          do
              gh actions-cache delete ${cacheKeysArray[$i]} -R $REPO -B $BRANCH --confirm
          done

          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          KEY: ${{ matrix.key }}
          BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge
